article/urls.py
from django.urls import path, include
from . import views
app_name = 'article'

urlpatterns = [
    path('polls', views.IndexView.as_view(), name='index'),
    path('polls/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('polls/<int:pk>/results/', views.ResultView.as_view(), name='results'),
    path('polls/<int:question_id>/vote/', views.vote, name='vote'),
]

article_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("poll.urls"))
]

poll/urls.py
from django.urls import path, include
from . import views
app_name = 'poll'

urlpatterns = [
    path('polls', views.IndexView.as_view(), name='index'),
    path('polls/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('polls/<int:pk>/results/', views.ResultView.as_view(), name='results'),
    path('polls/<int:question_id>/vote/', views.vote, name='vote'),
]

article/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('date published')

    def __str__(self):

        return self.question_text

    def was_published_recently(self):
        """
        This method returns True if published date is less than or equals to today otherwise 
        returns False for days in the future
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

poll/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('date published')

    def __str__(self):

        return self.question_text

    def was_published_recently(self):
        """
        This method returns True if published date is less than or equals to today otherwise 
        returns False for days in the future
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'published recently'
        
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

article/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone


# def index(request):
#     template = 'article/index.html'
#     latest_questions = Question.objects.order_by("-pub_date")[:5]
#     return render(request, template, {'latest_questions': latest_questions})

# def detail(request, question_id):
#     template = 'article/detail.html'
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, template, {'question': question})


# def results(request, question_id):
#     template = 'article/result.html'
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, template, {'question': question})

class IndexView(generic.ListView):
    template_name = 'article/index.html'
    context_object_name = 'latest_questions'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())\
                                .order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'article/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultView(generic.DetailView):
    model = Question
    template_name = 'article/result.html'


def vote(request, question_id):
    template = 'article/detail.html'
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, template, {'question': question,
                                          'error_message': "you didn't select a choice"})
    else:
        selected_choice.vote += 1
        selected_choice.save()

    return HttpResponseRedirect(reverse('article:results', args=(question.id,)))

poll/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone


# def index(request):
#     template = 'poll/index.html'
#     latest_questions = Question.objects.order_by("-pub_date")[:5]
#     return render(request, template, {'latest_questions': latest_questions})

# def detail(request, question_id):
#     template = 'poll/detail.html'
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, template, {'question': question})


# def results(request, question_id):
#     template = 'poll/result.html'
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, template, {'question': question})

class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_questions'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())\
                                .order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultView(generic.DetailView):
    model = Question
    template_name = 'poll/result.html'


def vote(request, question_id):
    template = 'poll/detail.html'
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, template, {'question': question,
                                          'error_message': "you didn't select a choice"})
    else:
        selected_choice.vote += 1
        selected_choice.save()

    return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

article/templates/article/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'article:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    <input type="submit" value="Vote">
</form>

<!-- <ul>
    {% for choice in question.choice_set.all %}
<li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul> -->

article/templates/article/result.html
<h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.vote }} vote{{ choice.vote|pluralize }}</li>
        {% endfor %}
    </ul>
<a href="{% url 'article:detail' question.id %}">Vote again?</a>

poll/templates/poll/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'poll:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <h4>
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            </h4>
        {% endfor %}
    <input type="submit" value="Vote">
</form>

<!-- <ul>
    {% for choice in question.choice_set.all %}
<li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul> -->

poll/templates/poll/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'poll/style.css' %}" type="text/css">

{% if latest_questions %}

<ul>
    {% for question in latest_questions %}
        <li>
            <h3>
                <a href="{% url 'poll:detail' question.id %}">
                    {{ question.question_text }}
                </a>
            </h3>
        </li>
    {% endfor %}
</ul>

{% else %}
    No question available
{% endif %}

poll/templates/poll/result.html
<h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <h4>
            <li>{{ choice.choice_text }} -- {{ choice.vote }} vote{{ choice.vote|pluralize }}</li>
        </h4>
        {% endfor %}
    </ul>
<a href="{% url 'poll:detail' question.id %}">Vote again?</a>